In [1]:
!pip install factor_analyzer

Requirement already satisfied: factor_analyzer in c:\anaconda3\lib\site-packages (0.5.1)
Requirement already satisfied: pandas in c:\anaconda3\lib\site-packages (from factor_analyzer) (2.3.3)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from factor_analyzer) (1.16.3)
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from factor_analyzer) (2.3.5)
Requirement already satisfied: scikit-learn in c:\anaconda3\lib\site-packages (from factor_analyzer) (1.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\anaconda3\lib\site-packages (from pandas->factor_analyzer) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\anaconda3\lib\site-packages (from pandas->factor_analyzer) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\anaconda3\lib\site-packages (from pandas->factor_analyzer) (2025.2)
Requirement already satisfied: six>=1.5 in c:\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->factor_analyzer) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\anaconda3\lib\site-packages (from scikit-learn->factor_analyzer) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\anaconda3\lib\site-packages (from scikit-learn->factor_analyzer) (3.5.0)

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv(r"C:\Users\huawei\Downloads\data-final.csv", sep="\t")

In [10]:
df

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,...,dateload,screenw,screenh,introelapse,testelapse,endelapse,IPC,country,lat_appx_lots_of_err,long_appx_lots_of_err
0,4.0,1.0,5.0,2.0,5.0,1.0,5.0,2.0,4.0,1.0,...,2016-03-03 02:01:01,768.0,1024.0,9.0,234.0,6,1,GB,51.5448,0.1991
1,3.0,5.0,3.0,4.0,3.0,3.0,2.0,5.0,1.0,5.0,...,2016-03-03 02:01:20,1360.0,768.0,12.0,179.0,11,1,MY,3.1698,101.706
2,2.0,3.0,4.0,4.0,3.0,2.0,1.0,3.0,2.0,5.0,...,2016-03-03 02:01:56,1366.0,768.0,3.0,186.0,7,1,GB,54.9119,-1.3833
3,2.0,2.0,2.0,3.0,4.0,2.0,2.0,4.0,1.0,4.0,...,2016-03-03 02:02:02,1920.0,1200.0,186.0,219.0,7,1,GB,51.75,-1.25
4,3.0,3.0,3.0,3.0,5.0,3.0,3.0,5.0,3.0,4.0,...,2016-03-03 02:02:57,1366.0,768.0,8.0,315.0,17,2,KE,1.0,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015336,4.0,2.0,4.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,...,2018-11-08 12:04:58,1920.0,1080.0,3.0,160.0,10,2,US,39.9883,-75.2208
1015337,4.0,3.0,4.0,3.0,3.0,3.0,4.0,4.0,3.0,3.0,...,2018-11-08 12:07:18,1920.0,1080.0,3.0,122.0,7,1,US,38.0,-97.0
1015338,4.0,2.0,4.0,3.0,5.0,1.0,4.0,2.0,4.0,4.0,...,2018-11-08 12:07:49,1920.0,1080.0,2.0,135.0,12,6,US,36.1473,-86.777
1015339,2.0,4.0,3.0,4.0,2.0,2.0,1.0,4.0,2.0,4.0,...,2018-11-08 12:08:34,1920.0,1080.0,6.0,212.0,8,1,US,34.1067,-117.8067
1015340,4.0,2.0,4.0,2.0,4.0,1.0,4.0,2.0,4.0,4.0,...,2018-11-08 12:08:45,1920.0,1080.0,3.0,176.0,9,1,US,38.0,-97.0

In [11]:
cols = [col for col in df.columns 
        if col.startswith(("EXT","EST","AGR","CSN","OPN")) 
        and not col.endswith("_E")]

df_questions = df[cols]

df_questions.shape
df_questions.head()

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,...,OPN1,OPN2,OPN3,OPN4,OPN5,OPN6,OPN7,OPN8,OPN9,OPN10
0,4.0,1.0,5.0,2.0,5.0,1.0,5.0,2.0,4.0,1.0,...,5.0,1.0,4.0,1.0,4.0,1.0,5.0,3.0,4.0,5.0
1,3.0,5.0,3.0,4.0,3.0,3.0,2.0,5.0,1.0,5.0,...,1.0,2.0,4.0,2.0,3.0,1.0,4.0,2.0,5.0,3.0
2,2.0,3.0,4.0,4.0,3.0,2.0,1.0,3.0,2.0,5.0,...,5.0,1.0,2.0,1.0,4.0,2.0,5.0,3.0,4.0,4.0
3,2.0,2.0,2.0,3.0,4.0,2.0,2.0,4.0,1.0,4.0,...,4.0,2.0,5.0,2.0,3.0,1.0,4.0,4.0,3.0,3.0
4,3.0,3.0,3.0,3.0,5.0,3.0,3.0,5.0,3.0,4.0,...,5.0,1.0,5.0,1.0,5.0,1.0,5.0,3.0,5.0,5.0

In [14]:
df_sample = df_questions.sample(n=2000, random_state=42)
df_sample

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,...,OPN1,OPN2,OPN3,OPN4,OPN5,OPN6,OPN7,OPN8,OPN9,OPN10
564534,3.0,3.0,3.0,2.0,3.0,2.0,2.0,3.0,3.0,5.0,...,4.0,1.0,3.0,5.0,4.0,2.0,4.0,4.0,4.0,3.0
609728,3.0,2.0,4.0,4.0,4.0,1.0,3.0,5.0,2.0,4.0,...,3.0,1.0,4.0,1.0,4.0,2.0,5.0,3.0,4.0,4.0
152274,4.0,2.0,4.0,3.0,3.0,1.0,2.0,3.0,4.0,4.0,...,4.0,2.0,4.0,2.0,3.0,2.0,4.0,3.0,4.0,4.0
902438,4.0,2.0,4.0,2.0,3.0,1.0,4.0,3.0,4.0,3.0,...,4.0,1.0,5.0,1.0,5.0,1.0,4.0,2.0,5.0,4.0
597988,1.0,5.0,3.0,5.0,1.0,3.0,1.0,5.0,1.0,5.0,...,5.0,2.0,5.0,2.0,4.0,2.0,4.0,4.0,4.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475501,4.0,2.0,4.0,2.0,5.0,1.0,4.0,3.0,4.0,2.0,...,3.0,2.0,2.0,3.0,4.0,2.0,5.0,1.0,4.0,4.0
761496,2.0,1.0,4.0,2.0,4.0,1.0,2.0,2.0,4.0,2.0,...,5.0,1.0,5.0,1.0,3.0,1.0,3.0,5.0,5.0,5.0
599905,3.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,4.0,3.0,...,5.0,1.0,4.0,1.0,4.0,2.0,5.0,5.0,4.0,4.0
33266,2.0,2.0,4.0,3.0,4.0,2.0,4.0,5.0,2.0,3.0,...,4.0,2.0,4.0,2.0,3.0,1.0,3.0,4.0,5.0,4.0
596942,2.0,4.0,4.0,4.0,4.0,2.0,2.0,4.0,3.0,4.0,...,3.0,1.0,5.0,1.0,3.0,1.0,4.0,1.0,4.0,4.0

In [15]:
from factor_analyzer import FactorAnalyzer

fa = FactorAnalyzer(rotation=None)
fa.fit(df_sample)

ev, v = fa.get_eigenvalues()

C:\anaconda3\Lib\site-packages\sklearn\utils\deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [16]:
ev

array([7.42245759, 4.86634298, 3.8387314 , 3.46142238, 2.8942334 ,
       1.87370249, 1.30682247, 1.08102732, 1.00285146, 0.97985179,
       0.90026575, 0.86369794, 0.84173923, 0.81183517, 0.78392662,
       0.75551878, 0.74002363, 0.72475673, 0.71832045, 0.70051452,
       0.65720895, 0.62509574, 0.61759062, 0.5970314 , 0.57667902,
       0.56417877, 0.53355355, 0.5275498 , 0.51574101, 0.49952583,
       0.48662433, 0.48067637, 0.46642187, 0.46372463, 0.45183109,
       0.43103096, 0.42800734, 0.41019961, 0.40081942, 0.39058211,
       0.38486721, 0.36622407, 0.35956812, 0.35616781, 0.33701886,
       0.33581418, 0.32592238, 0.31828938, 0.29319433, 0.23081914])

In [17]:
fa = FactorAnalyzer(n_factors=5, rotation='varimax')
fa.fit(df_sample)

C:\anaconda3\Lib\site-packages\sklearn\utils\deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

FactorAnalyzer(n_factors=5, rotation='varimax', rotation_kwargs={})

In [18]:
import pandas as pd

loadings = pd.DataFrame(
    fa.loadings_,
    index=df_sample.columns,
    columns=[f'Factor{i+1}' for i in range(5)]
)

loadings.head(100)

        Factor1   Factor2   Factor3   Factor4   Factor5
EXT1   0.707762 -0.011165  0.069146  0.032314  0.020660
EXT2  -0.665559  0.037500 -0.143546 -0.009791  0.045651
EXT3   0.668705 -0.204463  0.223174  0.001155  0.121044
EXT4  -0.695298  0.162675 -0.047420  0.042594  0.010777
EXT5   0.718344 -0.054966  0.188808  0.112353  0.095242
EXT6  -0.537156  0.124815 -0.126032 -0.191978  0.025749
EXT7   0.717812 -0.073466  0.136448  0.057071  0.094204
EXT8  -0.525173  0.073150  0.035814  0.013740  0.088151
EXT9   0.629891 -0.015490 -0.037262  0.167378 -0.032157
EXT10 -0.678229  0.223279 -0.056260  0.030063 -0.018399
EST1  -0.141064  0.662717  0.124444 -0.077634  0.020843
EST2   0.187848 -0.444462 -0.044956  0.068135  0.011748
EST3  -0.146150  0.598822  0.187783 -0.001480  0.058322
EST4   0.168739 -0.269730 -0.045996 -0.007592  0.103934
EST5  -0.019032  0.510410 -0.001805 -0.067027 -0.050415
EST6  -0.072754  0.723008  0.044598 -0.073517 -0.065233
EST7   0.012732  0.715158 -0.038720 -0.025183 -0.092558
EST8  -0.025466  0.726655 -0.052747 -0.008566 -0.100643
EST9  -0.044529  0.705073 -0.188086 -0.036016  0.032182
EST10 -0.284290  0.616720  0.019581  0.119068 -0.144448
AGR1   0.031773  0.056646 -0.450527 -0.059041  0.072298
AGR2   0.344950 -0.016505  0.529238  0.127104  0.009614
AGR3   0.129454  0.253130 -0.451956  0.074987 -0.163482
AGR4   0.051819  0.111289  0.776245  0.051655  0.050204
AGR5  -0.121375  0.015267 -0.625299  0.018706  0.025292
AGR6   0.002808  0.213482  0.579537 -0.026504  0.034124
AGR7  -0.272706  0.151929 -0.601504  0.016480  0.026041
AGR8   0.137641  0.065134  0.531353  0.093015  0.145249
AGR9   0.129955  0.162732  0.678959  0.073833  0.084721
AGR10  0.336474 -0.017556  0.432242  0.160172  0.168974
CSN1   0.010689 -0.068935  0.029926  0.139408  0.576736
CSN2   0.053983  0.144817  0.063930  0.169299 -0.520811
CSN3  -0.012858  0.015091  0.044818  0.292248  0.416314
CSN4  -0.035248  0.399841 -0.062947  0.033618 -0.487089
CSN5   0.113898 -0.048169  0.031816 -0.049416  0.612266
CSN6   0.044100  0.204189  0.044342  0.123889 -0.543978
CSN7  -0.036783  0.162995  0.046068  0.076213  0.551909
CSN8  -0.043373  0.254591 -0.110350 -0.004824 -0.413916
CSN9   0.026722  0.089913  0.100903 -0.030801  0.605616
CSN10  0.022954  0.013160  0.059149  0.340957  0.457934
OPN1   0.043972 -0.014256 -0.041349  0.609887  0.040300
OPN2   0.008548  0.301182 -0.016329 -0.492110  0.033810
OPN3   0.033167  0.117824  0.096723  0.492142 -0.065654
OPN4   0.062872  0.163367 -0.079715 -0.403848  0.108231
OPN5   0.245191 -0.063765 -0.016647  0.543539  0.171629
OPN6  -0.049546  0.117603 -0.112643 -0.403124  0.094498
OPN7   0.090275 -0.109832 -0.018509  0.481597  0.231592
OPN8   0.018442  0.059010 -0.140464  0.587188 -0.013658
OPN9  -0.112109  0.165352  0.175369  0.428121  0.088369
OPN10  0.204133  0.023875  0.069676  0.637234  0.034196

In [20]:
!pip install numpy

Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (2.3.5)

In [21]:
import numpy as np

In [22]:
strong_loadings = loadings.apply(lambda x: np.where(abs(x) > 0.4, x, 0))
strong_loadings.head(10)

        Factor1  Factor2  Factor3  Factor4  Factor5
EXT1   0.707762      0.0      0.0      0.0      0.0
EXT2  -0.665559      0.0      0.0      0.0      0.0
EXT3   0.668705      0.0      0.0      0.0      0.0
EXT4  -0.695298      0.0      0.0      0.0      0.0
EXT5   0.718344      0.0      0.0      0.0      0.0
EXT6  -0.537156      0.0      0.0      0.0      0.0
EXT7   0.717812      0.0      0.0      0.0      0.0
EXT8  -0.525173      0.0      0.0      0.0      0.0
EXT9   0.629891      0.0      0.0      0.0      0.0
EXT10 -0.678229      0.0      0.0      0.0      0.0

In [23]:
loadings['Factor1'].sort_values(ascending=False)

EXT5     0.718344
EXT7     0.717812
EXT1     0.707762
EXT3     0.668705
EXT9     0.629891
AGR2     0.344950
AGR10    0.336474
OPN5     0.245191
OPN10    0.204133
EST2     0.187848
EST4     0.168739
AGR8     0.137641
AGR9     0.129955
AGR3     0.129454
CSN5     0.113898
OPN7     0.090275
OPN4     0.062872
CSN2     0.053983
AGR4     0.051819
CSN6     0.044100
OPN1     0.043972
OPN3     0.033167
AGR1     0.031773
CSN9     0.026722
CSN10    0.022954
OPN8     0.018442
EST7     0.012732
CSN1     0.010689
OPN2     0.008548
AGR6     0.002808
CSN3    -0.012858
EST5    -0.019032
EST8    -0.025466
CSN4    -0.035248
CSN7    -0.036783
CSN8    -0.043373
EST9    -0.044529
OPN6    -0.049546
EST6    -0.072754
OPN9    -0.112109
AGR5    -0.121375
EST1    -0.141064
EST3    -0.146150
AGR7    -0.272706
EST10   -0.284290
EXT8    -0.525173
EXT6    -0.537156
EXT2    -0.665559
EXT10   -0.678229
EXT4    -0.695298
Name: Factor1, dtype: float64

In [24]:
loadings['Factor2'].sort_values(ascending=False)

EST8     0.726655
EST6     0.723008
EST7     0.715158
EST9     0.705073
EST1     0.662717
EST10    0.616720
EST3     0.598822
EST5     0.510410
CSN4     0.399841
OPN2     0.301182
CSN8     0.254591
AGR3     0.253130
EXT10    0.223279
AGR6     0.213482
CSN6     0.204189
OPN9     0.165352
OPN4     0.163367
CSN7     0.162995
AGR9     0.162732
EXT4     0.162675
AGR7     0.151929
CSN2     0.144817
EXT6     0.124815
OPN3     0.117824
OPN6     0.117603
AGR4     0.111289
CSN9     0.089913
EXT8     0.073150
AGR8     0.065134
OPN8     0.059010
AGR1     0.056646
EXT2     0.037500
OPN10    0.023875
AGR5     0.015267
CSN3     0.015091
CSN10    0.013160
EXT1    -0.011165
OPN1    -0.014256
EXT9    -0.015490
AGR2    -0.016505
AGR10   -0.017556
CSN5    -0.048169
EXT5    -0.054966
OPN5    -0.063765
CSN1    -0.068935
EXT7    -0.073466
OPN7    -0.109832
EXT3    -0.204463
EST4    -0.269730
EST2    -0.444462
Name: Factor2, dtype: float64

In [25]:
loadings['Factor3'].sort_values(ascending=False)

AGR4     0.776245
AGR9     0.678959
AGR6     0.579537
AGR8     0.531353
AGR2     0.529238
AGR10    0.432242
EXT3     0.223174
EXT5     0.188808
EST3     0.187783
OPN9     0.175369
EXT7     0.136448
EST1     0.124444
CSN9     0.100903
OPN3     0.096723
OPN10    0.069676
EXT1     0.069146
CSN2     0.063930
CSN10    0.059149
CSN7     0.046068
CSN3     0.044818
EST6     0.044598
CSN6     0.044342
EXT8     0.035814
CSN5     0.031816
CSN1     0.029926
EST10    0.019581
EST5    -0.001805
OPN2    -0.016329
OPN5    -0.016647
OPN7    -0.018509
EXT9    -0.037262
EST7    -0.038720
OPN1    -0.041349
EST2    -0.044956
EST4    -0.045996
EXT4    -0.047420
EST8    -0.052747
EXT10   -0.056260
CSN4    -0.062947
OPN4    -0.079715
CSN8    -0.110350
OPN6    -0.112643
EXT6    -0.126032
OPN8    -0.140464
EXT2    -0.143546
EST9    -0.188086
AGR1    -0.450527
AGR3    -0.451956
AGR7    -0.601504
AGR5    -0.625299
Name: Factor3, dtype: float64

In [26]:
loadings['Factor4'].sort_values(ascending=False)

OPN10    0.637234
OPN1     0.609887
OPN8     0.587188
OPN5     0.543539
OPN3     0.492142
OPN7     0.481597
OPN9     0.428121
CSN10    0.340957
CSN3     0.292248
CSN2     0.169299
EXT9     0.167378
AGR10    0.160172
CSN1     0.139408
AGR2     0.127104
CSN6     0.123889
EST10    0.119068
EXT5     0.112353
AGR8     0.093015
CSN7     0.076213
AGR3     0.074987
AGR9     0.073833
EST2     0.068135
EXT7     0.057071
AGR4     0.051655
EXT4     0.042594
CSN4     0.033618
EXT1     0.032314
EXT10    0.030063
AGR5     0.018706
AGR7     0.016480
EXT8     0.013740
EXT3     0.001155
EST3    -0.001480
CSN8    -0.004824
EST4    -0.007592
EST8    -0.008566
EXT2    -0.009791
EST7    -0.025183
AGR6    -0.026504
CSN9    -0.030801
EST9    -0.036016
CSN5    -0.049416
AGR1    -0.059041
EST5    -0.067027
EST6    -0.073517
EST1    -0.077634
EXT6    -0.191978
OPN6    -0.403124
OPN4    -0.403848
OPN2    -0.492110
Name: Factor4, dtype: float64

In [27]:
loadings['Factor5'].sort_values(ascending=False)

CSN5     0.612266
CSN9     0.605616
CSN1     0.576736
CSN7     0.551909
CSN10    0.457934
CSN3     0.416314
OPN7     0.231592
OPN5     0.171629
AGR10    0.168974
AGR8     0.145249
EXT3     0.121044
OPN4     0.108231
EST4     0.103934
EXT5     0.095242
OPN6     0.094498
EXT7     0.094204
OPN9     0.088369
EXT8     0.088151
AGR9     0.084721
AGR1     0.072298
EST3     0.058322
AGR4     0.050204
EXT2     0.045651
OPN1     0.040300
OPN10    0.034196
AGR6     0.034124
OPN2     0.033810
EST9     0.032182
AGR7     0.026041
EXT6     0.025749
AGR5     0.025292
EST1     0.020843
EXT1     0.020660
EST2     0.011748
EXT4     0.010777
AGR2     0.009614
OPN8    -0.013658
EXT10   -0.018399
EXT9    -0.032157
EST5    -0.050415
EST6    -0.065233
OPN3    -0.065654
EST7    -0.092558
EST8    -0.100643
EST10   -0.144448
AGR3    -0.163482
CSN8    -0.413916
CSN4    -0.487089
CSN2    -0.520811
CSN6    -0.543978
Name: Factor5, dtype: float64